---
title: "MA_Demographics_Siegel"
author: "Siegel"
date: "2023-10-13"
output: html_document
---

### packages
## install packages
install.packages("psych")
install.packages("tidyverse")
install.packages("openxlsx")
install.packages("lubridate")

## activate packages
library(readxl)
library(psych)
library(tidyverse)
library(openxlsx)
library(lubridate)


### data organisation
## import data
data_raw <- read_excel("data/MA_data_raw.xlsx")

## remove empty cells and drop outs
# empty cells
empty_cells <- c(56, 57, 58, 59, 60)
data_raw <- data_raw[-empty_cells,]

# drop outs
drop_out <- c(30, 41, 44, 53)
data_raw <- data_raw[-drop_out,]

## creating new data frame
MA_demo_data <- data_raw[c('Patient',
                      'ID',
                      'Sex',
                      'Onset',
                      'Test',
                      'Age',
                      'Etiol',
                      'Hemi',
                      'Lesvol',
                      'TokenTest_corr',
                      'AAT_SV',
                      'Aphasia',
                      'Severity')]
                      
## inspecting the structure of the data frame
str(MA_demo_data)


### descriptive statistics - demographics
## describe data
select(.data = MA_demo_data, c(Gender:Severity))%>%describe(.)

## Create variable 'Months since Onset (MSO)'
# Calculate 'Months since Onset'
MSO <- interval(MA_demo_data$Test, MA_demo_data$Onset) %/% months(1)

# change the operator
MSO_pos <- MSO
MSO_pos[sapply(MSO_pos, is.numeric)] <- MSO_pos[sapply(MSO_pos, is.numeric)]*-1

# create new variable MSO
MA_demo_data$MSO <- MSO_pos

## Mean and SD of age, lesion volume, months since onset, TT and SV (AAT)
# Age
mean(MA_demo_data$Age)
sd(MA_demo_data$Age)

# Lesion volume
mean(MA_demo_data$Lesvol)
sd(MA_demo_data$Lesvol)

# Months since Onset (MSO)
mean(MA_demo_data$MSO)
sd(MA_demo_data$MSO)

# TT (AAT)
# new data frame due to missing data of one participant
data_TT <- MA_demo_data

# empty cell
empty_cell_TT <- c(9)
data_TT <- data_TT[-empty_cell_TT,]

# mean and SD
mean(data_TT$TokenTest_corr)
sd(data_TT$TokenTest_corr)

# SV (AAT)
# new data frame due to missing data of one participant
data_SV <- MA_demo_data

# empty cell
empty_cell_SV <- c(31)
data_SV <- data_SV[-empty_cell_SV,]

# mean and SD
mean(data_SV$AAT_SV)
sd(data_SV$AAT_SV)

## Minimum and maximum of age and MSO
# Age
min(MA_demo_data$Age)
max(MA_demo_data$Age)

# MSO
min(MA_demo_data$MSO)
max(MA_demo_data$MSO)

## frequency table (absolute & relative)
# Sex
Freq_a_Sex <- table(MA_demo_data$Sex)
Freq_r_Sex <- round(prop.table (table(MA_demo_data$Sex))*100,4)
table_Sex <- cbind(Freq_a_Sex, Freq_r_Sex)

# Aetiology
Freq_a_Etiol <- table(MA_demo_data$Etiol)
Freq_r_Etiol <- round(prop.table (table(MA_demo_data$Etiol))*100,4)
table_Etiol <- cbind(Freq_a_Etiol, Freq_r_Etiol)

# Hemisphere
Freq_a_Hemi <- table(MA_demo_data$Hemi)
Freq_r_Hemi <- round(prop.table (table(MA_demo_data$Hemi))*100,4)
table_Hemi <- cbind(Freq_a_Hemi, Freq_r_Hemi)

# Aphasia
Freq_a_Aphasia <- table(MA_demo_data$Aphasia)
Freq_r_Aphasia <- round(prop.table (table(MA_demo_data$Aphasia))*100,4)
table_Aphasia <- cbind(Freq_a_Aphasia, Freq_r_Aphasia)

# Severity
Freq_a_Severity <- table(MA_demo_data$Severity)
Freq_r_Severity <- round(prop.table (table(MA_demo_data$Severity))*100,4)
table_Severity <- cbind(Freq_a_Severity, Freq_r_Severity)


### export MA_demo_data
write.xlsx(MA_demo_data, '/Users/piamariesiegel/Desktop/Master Studium/Masterarbeit/Statistics_MA_Thesis/data/MA_demo_data.xlsx')