---
title: "Behavioral analysis"
author: "Sandra Martin"
date: "`r Sys.Date()`"
output: html_document:
  toc: true
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE, echo=FALSE}
rm(list= ls()) # clear all 
knitr::opts_chunk$set()
options(scipen = 999)
```

# Load packages
```{r packages, message=FALSE, warning=TRUE}
library(here)
library(plyr)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(lme4)
library(emmeans)
library(ggeffects)
library(stringr)
library(fitdistrplus)
library(see)
library(cowplot)
library(performance)
library(sjPlot)
```


```{r Theme for plots, include=FALSE}
apatheme <- theme_bw()+
  theme(plot.title = element_blank(), panel.grid.major=element_blank(), panel.grid.minor=element_blank(),
        panel.border=element_blank(),axis.line=element_line(),
        text=element_text(family='sans',size=18)) #panel.grid.major=element_blank(),

today <- Sys.Date()
today <- format(today, format="%y%m%d")

palet_task <- c("#BBBBBB","#994455")
palet_task_cong <- c("#BBBBBB","#5D5D5D", "#994455", "#4d222b")

output_path = here::here("Plots/")

# creating a function for std.error
std.error <- function(x, na.rm = TRUE){sd(x, na.rm = TRUE)/sqrt(length(x[!is.na(x)]))}
```

# Load data
```{r Load R data}
# full df including demographic and npsy dara
load(here::here("RData/all_files_01_2024.RData"))
```

```{r Read in data, message=FALSE, include=FALSE, eval=FALSE}
# There was a mix-up with the button assignments for the first 20 participants with even participant numbers (e.g., 002, 004, etc.). This needs to be fixed first since accuracy was assigned wrong in these participants. That's why we're first reading in the files of these 20 participants, change accuracy labels, then read in the other participants and finally merge both data frames. 
# Read in data for files with errors
path = here::here("raw_data/subsample_even_participants_till20/")

error_files <- ""
seeds <- list.files(path = path, pattern = "MDN_APH_")

for (i in 1:length(seeds)) {
  filedir <- seeds[i]
  seed <- read.table(paste0(path, "/", filedir), skip = 7, header = T, sep = "\t", na.strings = "NaN")
  if ("correctness" %in% colnames(seed)) {
  seed <- seed %>% 
    dplyr::rename(congruency = correctness)
  }
  infos <- read.table(paste0(path, "/", filedir), fill = T)
  seed$sub <- infos$V2[infos$V1 == "Subject:"]
  seed$run <- infos$V2[infos$V1 == "Run:"]
  seed$buttons <- infos$V2[infos$V1 == "Buttons:"]
  error_files <- rbind(error_files, seed)
}

error_files <- error_files[-1,]     # delete first row of df since it's only NAs

# now switch accuracy information in this df: labelled "incorrect" was actually correct and labelled "correct" was actually incorrect 
# --> reason for this mix-up was due to wrong button assignments: Presentation thought we were switching correct and incorrect buttons across participants when in fact we were not
error_files <- error_files %>% 
  mutate(accuracy_new = case_when(
    congruency == "correct" & button_response == 2 ~ "correct",
    congruency == "correct" & button_response == 1 ~ "incorrect",
    congruency == "incorrect" & button_response == 2 ~ "incorrect",
    congruency == "incorrect" & button_response == 1 ~ "correct",
    NA ~ NA
  ))

error_files$accuracy <- error_files$accuracy_new
error_files <- error_files %>% 
  dplyr::select(-c("accuracy_new"))


# Read in data
path = here::here("raw_data/")

all_files <- ""
seeds <- list.files(path = path, pattern = "MDN_APH_")

for (i in 1:length(seeds)) {
  filedir <- seeds[i]
  seed <- read.table(paste0(path, "/", filedir), skip = 7, header = T, sep = "\t", na.strings = "NaN")
  if ("correctness" %in% colnames(seed)) {
  seed <- seed %>% 
    dplyr::rename(congruency = correctness)
  }
  infos <- read.table(paste0(path, "/", filedir), fill = T)
  seed$sub <- infos$V2[infos$V1 == "Subject:"]
  seed$run <- infos$V2[infos$V1 == "Run:"]
  seed$buttons <- infos$V2[infos$V1 == "Buttons:"]
  all_files <- rbind(all_files, seed)
}


all_files <- all_files[-1,]     # delete first row of df since it's only NAs

# now merge all_files with error_files to have complete df
all_files <- full_join(all_files, error_files)

all_files$time_audio <- as.numeric(all_files$time_audio)
all_files$length_audio <- as.numeric(all_files$length_audio)
all_files$time_picture <- as.numeric(all_files$time_picture)
all_files$response_time <- as.numeric(all_files$response_time)
all_files <- dplyr::rename(all_files, 
                    response_time_absolute = response_time,
                    response_time = absolute_response_time)
all_files$response_time_absolute <- as.numeric(all_files$response_time_absolute)
all_files$response_time <- as.numeric(all_files$response_time)
all_files$time_ISI <- as.numeric(all_files$time_ISI)
all_files$sub <- str_pad(all_files$sub, 3, "left", "0")
all_files$sub <- as.factor(all_files$sub)
all_files$run <- as.factor(all_files$run)
all_files$button_response <- as.factor(all_files$button_response)
all_files$accuracy <- as.factor(all_files$accuracy)
all_files$condition <- as.factor(all_files$condition)
all_files$congruency[all_files$congruency == "correct"] <- "congruent"
all_files$congruency[all_files$congruency == "incorrect"] <- "incongruent"
all_files$congruency <- as.factor(all_files$congruency)
all_files$category <- as.factor(all_files$category)
all_files$buttons <- as.factor(all_files$buttons)
all_files <- all_files[, c(18, 19, 10, 11, 1:9, 12:17, 20)]


## Count NA values
df_na <- all_files %>% 
  group_by(sub, run, condition) %>% 
  summarise(n_trials = n(), n_na = sum(is.na(response_time) == TRUE), prop = sum(is.na(response_time) == TRUE)/n())


## Count errors
#df_acc <- all_files %>% 
#  group_by(sub, condition) %>% 
#  summarise(n_trials = n(), n_corr = sum(accuracy == "correct", na.rm = T), prop = sum(accuracy == "correct", na.rm = T)/n())


#---- read in demographic and neuropsychological data ----
df_npsy <- read.table(here::here("raw_data/Npsy_data_01_24.txt"), header = T, sep = "\t")
df_npsy$sub <- str_pad(df_npsy$sub, width = 3, side = "left", pad = "0")

#---- merge dfs ----
all_files <- full_join(all_files, df_npsy)

# sort columns
all_files <- all_files[,c(1,21:26,36:38,2:20,27:35,39:51)]

# save df
save(all_files, file = 'RData/all_files_01_2024.RData')
```

# RT analysis
## Prepare df for reaction time analysis
```{r}
# remove NA values
df_RT <- all_files[!is.na(all_files$response_time),]

# remove incorrect answers
df_RT <- df_RT[df_RT$accuracy != "incorrect", ]

df_RT$response_time <- as.numeric(df_RT$response_time)

# remove RTs before picture was shown (equals rt = 0) and RTs below 100 ms
df_RT <- df_RT[!(df_RT$response_time_absolute < df_RT$time_picture),]
df_RT <- df_RT[!(df_RT$response_time < 100),]
```

## Plot
```{r}
# relevel factors
df_RT$condition <- factor(df_RT$condition, levels = c("WPM", "FPM"))

# Create summary df for RT data incl baseline
summary_rt_full <- df_RT %>% group_by(condition) %>% 
  summarise(mean_rt = mean(response_time, na.rm = TRUE), 
            md_rt = median(response_time, na.rm = TRUE),
            SD_rt = sd(response_time, na.rm = TRUE), 
            var_rt = var(response_time, na.rm = TRUE),
            std.error_rt = std.error(response_time, na.rm = TRUE))

# Plot by Task
RT_cond <- ggplot(df_RT, aes(x = condition, y = response_time, fill = condition)) + 
  geom_violinhalf(aes(fill = condition), position = position_nudge(x = .2, y = 0), adjust = 1.5, trim = FALSE, alpha = .6, colour = NA) +
  geom_boxplot(alpha = 1, width = .3, colour = "black", outlier.shape = NA, position = position_dodge(width = 0.4)) +
  #geom_point(data=summary_rt_full, aes(x = condition, y = mean_rt, group = condition, colour = condition), shape=18, position = position_nudge(x = .2, y = 0)) +
  #geom_errorbar(data=summary_rt_full, aes(x = condition, y = mean_rt, group = condition, colour = condition, ymin = mean_rt - std.error_rt, ymax = mean_rt + std.error_rt), width = .05, position = position_nudge(x = .2, y = 0)) +
  scale_colour_manual(values =palet_task, labels = c("WPM", "FPM")) + 
  scale_fill_manual(values = palet_task, labels = c("WPM", "FPM")) +
  #scale_x_discrete(labels = c("Baseline", "Active", "Sham")) +
  #coord_cartesian(ylim = c(0, 3500)) +
  labs(y = "Reaction time in ms") +
  apatheme +
  theme(legend.position=("none"), 
        legend.title=element_blank(), 
        legend.text=element_text(size=12),
        axis.title.x = element_blank())
#  facet_wrap(~ congruency)
RT_cond
save_plot(RT_cond, file = here::here(paste0("Plots/RT_cond_", today, ".pdf")))
```

## Mixed-effects regression
### Describe distribution of RT and check if log-transformation is good
```{r Describe distribution of RT}
descdist(df_RT$response_time)
descdist(log(df_RT$response_time)) # log-transform leads to perfect normal dist
lattice::densityplot(log(df_RT$response_time))
```

### Model
```{r RT - Model including baseline session}
# relevel factors
df_RT$condition <- factor(df_RT$condition, levels = c("WPM", "FPM"))
df_RT$congruency <- factor(df_RT$congruency, levels = c("congruent", "incongruent"))
df_RT$age_z <- scale(df_RT$Age, scale = T)
df_RT$lesion_volume_z <- scale(df_RT$Lesion_volume, scale = T)

#---- Simple coding ----
# create a Simple Coding scheme
# https://stats.oarc.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/
# creating the contrast matrix manually by modifying the dummy coding scheme
c <- contr.treatment(2)
my.coding <- matrix(rep(1/2, 2), ncol = 1) 
my.simple <- c-my.coding

#assign the new coding scheme
contrasts(df_RT$condition) <- my.simple
contrasts(df_RT$congruency) <- my.simple

#---- fit model ----
m_RT1 <- lmer(log(response_time) ~ condition * congruency + run + lesion_volume_z + age_z + (1+ run + condition * congruency|sub) + (1|stimulus_audio) + (1|stimulus_picture), data = df_RT, REML = F, lmerControl(optimizer = "bobyqa"))

save(m_RT1, file = here::here(paste0("RData/m_RT_", today, ".RData")))

summary(m_RT1)

m_RT_res <- drop1(m_RT1, test = "Chisq")
save(m_RT_res, file = here::here(paste0("RData/m_RT_res", today, ".RData")))

# explore interaction
RT_emm <- emmeans(m_RT1, pairwise ~ congruency | condition, adjust = "holm", type = "response")

# plot model results
RT_int <- plot(ggemmeans(m_RT1, terms = c("condition")), collapse_group = c("run", "sub")) +
  scale_colour_manual(values = palet_task) +
  ylab("Reaction time in ms") +
  apatheme +
  theme(axis.title.x = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        legend.text=element_text(size=10))
RT_int
save_plot(RT_int, file = here::here(paste0("Plots/m_RT_cond_cong_", today, ".png")))

RT_lesionVol <- plot(ggemmeans(m_RT1, terms = c("lesion_volume_z")), limit.range = T) +
  ylab("Reaction time in ms") +
  xlab("Standardized lesion volume") +
  apatheme +
   theme(legend.position = "none",
        legend.title = element_blank())
RT_lesionVol
save_plot(RT_lesionVol, file = here::here(paste0("Plots/m_RT_lesionVol_", today, ".pdf")))

RT_run <- plot(ggemmeans(m_RT1, terms = c("run"))) +
  ylab("Reaction time in ms") +
  xlab("Run") +
  apatheme +
   theme(legend.position = "none",
        legend.title = element_blank())
RT_run
save_plot(RT_run, file = here::here(paste0("Plots/m_RT_run_", today, ".pdf")))

#---- create table output for model
tab_model(m_RT1)
```


# Accuracy analysis
## Prepare df for accuracy analysis
```{r}
# remove NA values
df_behav <- all_files[!is.na(all_files$response_time),]

# remove reactions before picture was shown (equals rt = 0)
df_behav <- df_behav[!(df_behav$response_time_absolute < df_behav$time_picture),]
```

## Plot
```{r}
# relevel factors
df_behav$condition <- factor(df_behav$condition, levels = c("WPM", "FPM"))

# Create summary df for accuracy
summary_acc <- df_behav %>% 
  group_by(sub, condition) %>% 
  summarise(n_trials = n(), n_corr = sum(accuracy == "correct", na.rm = T), prop = sum(accuracy == "correct", na.rm = T)/n())


# Plot by Task
Acc_cond <- ggplot(summary_acc, aes(x = condition, y = prop*100, fill = condition)) +
  geom_violinhalf(aes(fill = condition), position = position_nudge(x = 0.2, y = 0), alpha = 0.6, color = NA) +
  geom_boxplot(alpha = 1, width = .3, colour = "black", outlier.shape = NA, position = position_dodge(width = 0.4)) +
  scale_colour_manual(values =palet_task, labels = c("WPM", "FPM")) + 
  scale_fill_manual(values = palet_task, labels = c("WPM", "FPM")) +
  labs(y = "Accuracy in %") +
  apatheme +
  theme(legend.position=("none"), 
        legend.title=element_blank(), 
        legend.text=element_text(size=12),
        axis.title.x = element_blank())
# facet_wrap(~ congruency)
Acc_cond
save_plot(Acc_cond, file = here::here(paste0("Plots/Acc_cond_", today, ".pdf")))
```

## Mixed-effects regression
### Model
```{r Accuracy - Model}
# relevel factors
df_behav$condition <- factor(df_behav$condition, levels = c("WPM", "FPM"))
df_behav$congruency <- factor(df_behav$congruency, levels = c("congruent", "incongruent"))
df_behav$age_z <- scale(df_behav$Age, scale = T)
df_behav$Lesion_volume_z <- scale(df_behav$Lesion_volume, scale = T)

#---- Simple coding ----
# create a Simple Coding scheme
# https://stats.oarc.ucla.edu/r/library/r-library-contrast-coding-systems-for-categorical-variables/
# creating the contrast matrix manually by modifying the dummy coding scheme
c <- contr.treatment(2)
my.coding <- matrix(rep(1/2, 2), ncol = 1) 
my.simple <- c-my.coding

#assign the new coding scheme
contrasts(df_behav$condition) <- my.simple
contrasts(df_behav$congruency) <- my.simple

df_behav <- df_behav %>% 
  mutate(correct = case_when(
    accuracy == "correct" ~ 1,
    accuracy == "incorrect" ~ 0
  ))
df_behav$correct <- as.factor(df_behav$correct)

#---- Model ----
m_acc1 <- glmer(correct ~ condition * congruency + run + Lesion_volume_z + (1 + run + condition + congruency|sub) + (1|stimulus_audio) + (1|stimulus_picture), data = df_behav, family = binomial(link = "logit"), glmerControl(optimizer = "bobyqa")) # model with interaction in random slopes is singular

save(m_acc1, file = here::here(paste0("RData/m_acc_", today, ".RData")))

summary(m_acc1)

m_acc_res <- drop1(m_acc1, test = "Chisq")
save(m_acc_res, file = here::here(paste0("RData/m_acc_res", today, ".RData")))

## explore direction of interaction
acc_emm <- emmeans(m_acc1, pairwise ~ congruency | condition, adjust = "holm")

## plot model output
Acc_int <- plot(ggemmeans(m_acc1, terms = c("condition", "congruency"))) +
  scale_colour_manual(values = palet_task) +
  coord_cartesian(ylim = c(0.5, 1)) +
  ylab("Accuracy") +
  apatheme +
  theme(axis.title.x = element_blank(),
        legend.position = "bottom",
        legend.title = element_blank(),
        legend.text=element_text(size=10))
Acc_int
save_plot(Acc_int, file = here::here(paste0("Plots/m_Acc_cond_cong_", today, ".pdf")))
```
