---
title: "MA_Demographics_Siegel"
author: "Siegel"
date: "2023-10-13"
output: html_document
---
# Packages
```{r}
## Load packages
library(here)
library(readxl)
library(psych)
library(tidyverse)
library(openxlsx)
library(lubridate)
```

# Load data
```{r}
here::here()
load(here("./RData/all_files_11_2023.RData"))
data_raw <- all_files
```

# Data cleaning and preparing data frame
```{r}
## Creating new data frame with relevant variables
MA_demo_data <- data_raw[c('sub',
                           'ID',
                           'sex',
                           'onset',
                           'test',
                           'age',
                           'etiology',
                           'hemi',
                           'lesion_volume',
                           'TokenTest_corr',
                           'AAT_SV',
                           'aphasia',
                           'severity')]

## Merging data from trial level to subject level
df_demo_data <- MA_demo_data %>%
  group_by(ID) %>%
  distinct()

## Create as well as calculate variable 'Weeks since Onset (WSO)'
### Define variables 'test' and 'onset' as dates
df_demo_data$test <- as.Date(df_demo_data$test, format = "%d.%m.%y")
df_demo_data$onset <- as.Date(df_demo_data$onset, format = "%d.%m.%y")

### Calculate 'WSO' and define variable as a numeric data type
df_demo_data$WSO <- difftime(df_demo_data$test, df_demo_data$onset, units = "weeks")
df_demo_data$WSO <- as.numeric(df_demo_data$WSO)

### round to zero decimal places 
df_demo_data$WSO <- round(df_demo_data$WSO, 0)
```

# Descriptive statistics - demographics
```{r}
## Describe data
select(.data = df_demo_data, c(sex:WSO))%>%describe(.)

## Mean and SD of age, lesion volume, months since onset, TT and SV (AAT)
### Age
mean(df_demo_data$age)
sd(df_demo_data$age)

### Lesion volume
mean(df_demo_data$lesion_volume)
sd(df_demo_data$lesion_volume)

### Weeks since Onset (WSO)
mean(df_demo_data$WSO)
sd(df_demo_data$WSO)

### TT (AAT)
#### Remove NA trials
df_demo_data_TT <- filter(df_demo_data, !(is.na(TokenTest_corr)))

mean(df_demo_data_TT$TokenTest_corr)
sd(df_demo_data_TT$TokenTest_corr)

### SV (AAT)
#### Remove NA trials

df_demo_data_SV <- filter(df_demo_data, !(is.na(AAT_SV)))

mean(df_demo_data_SV$AAT_SV)
sd(df_demo_data_SV$AAT_SV)

## Minimum and maximum of age and WSO
### Age
min(df_demo_data$age)
max(df_demo_data$age)

### MSO
min(df_demo_data$WSO)
max(df_demo_data$WSO)

## Frequency table (absolute & relative)
### Sex
Freq_a_Sex <- table(df_demo_data$sex)
Freq_r_Sex <- round(prop.table (table(df_demo_data$sex))*100,4)
table_Sex <- cbind(Freq_a_Sex, Freq_r_Sex)

### Aetiology
Freq_a_Etiol <- table(df_demo_data$etiology)
Freq_r_Etiol <- round(prop.table (table(df_demo_data$etiology))*100,4)
table_Etiol <- cbind(Freq_a_Etiol, Freq_r_Etiol)

### Hemisphere
Freq_a_Hemi <- table(df_demo_data$hemi)
Freq_r_Hemi <- round(prop.table (table(df_demo_data$hemi))*100,4)
table_Hemi <- cbind(Freq_a_Hemi, Freq_r_Hemi)

### Aphasia
Freq_a_Aphasia <- table(df_demo_data$aphasia)
Freq_r_Aphasia <- round(prop.table (table(df_demo_data$aphasia))*100,4)
table_Aphasia <- cbind(Freq_a_Aphasia, Freq_r_Aphasia)

### Severity
Freq_a_Severity <- table(df_demo_data$severity)
Freq_r_Severity <- round(prop.table (table(df_demo_data$severity))*100,4)
table_Severity <- cbind(Freq_a_Severity, Freq_r_Severity)
```

# Export df_demo_data
```{r}
write.csv(df_demo_data, here("./RData/df_demo_data_PS.csv"), row.names = F)
```