---
title: "MA_LSM_data_preprocessing"
author: "Siegel"
date: "2023-11-14"
output: html_document
---
### packages

```{r}
## load packages
   library(here)
   library(readxl)
   library(psych)
   library(tidyverse)
   library(lubridate)
   library(dplyr)
```

### load data
```{r}
here::here()
load(here("./RData/all_files_11_2023.RData"))
data_raw <- all_files
```

### Data cleaning and preparing data frame
```{r}
## rename "ID" into "RegistryCode"
data_initial <- data_raw %>% 
  rename(RegistryCode = ID)
   
## Create variable 'Months since Onset (MSO)'
# Calculate 'Months since Onset'
data_initial$test <- as.Date(data_initial$test, format = "%d.%m.%y")
data_initial$onset <- as.Date(data_initial$onset, format = "%d.%m.%y")
data_initial$WSO <- difftime(data_initial$test, data_initial$onset, units = "weeks")
data_initial$WSO <- as.numeric(data_initial$WSO)

# remove NA trials --> participants were too slow to react on time or didn't react at all
data_initial <- filter(data_initial, !(is.na(accuracy)))

# make numeric variable for accuracy
data_initial$accuracy_num <- ifelse(data_initial$accuracy == "correct", 1, ifelse(data_initial$accuracy == "incorrect", 0, NA))
```


```{r}
### create dataframe for accuracy 

## SVR-LSM (WPM - accuracy)
# create new data frame with relevant variables 
data_WPM_acc <- data_initial[c('RegistryCode',
                                 'age',
                                 'WSO',
                                 'resolution',
                                 'severity',
                                 'condition',
                                 'accuracy_num')]

# Calculate mean of accuracy for each participant
df_WPM_acc_summary <- data_WPM_acc %>% 
  group_by(RegistryCode, condition) %>% 
  mutate(average_accuracy = mean(accuracy_num)) %>% 
  select(-accuracy_num) %>% 
  distinct()

df_WPM_acc_summary <- df_WPM_acc_summary %>% 
  pivot_wider(names_from = condition, values_from = average_accuracy)

# example way to filter df for specific subject
id4086 <- filter(data_initial, RegistryCode == "4086")

# extract data frame "data_WPM_acc"
write.csv(df_WPM_acc_summary, here("./RData/data_WPM_acc.csv"), row.names = F)
```

# prepare df for RT
```{r}
# remove incorrect trials from df
data_RT <- filter(data_initial, accuracy == "correct")

# create new data frame with relevant variables 
data_RT_cond <- data_RT[c('RegistryCode',
                                 'age',
                                 'WSO',
                                 'resolution',
                                 'severity',
                                 'condition',
                                 'response_time')]

# Calculate mean of accuracy for each participant
df_RT_cond_summary <- data_RT_cond %>% 
  group_by(RegistryCode, condition) %>% 
  mutate(average_RT = mean(response_time)) %>% 
  select(-response_time) %>% 
  distinct()

df_RT_cond_summary <- df_RT_cond_summary %>% 
  pivot_wider(names_from = condition, values_from = average_RT)

# extract data frame "data_WPM_acc"
write.csv(df_WPM_acc_summary, here("./RData/data_WPM_acc.csv"), row.names = F)

```





```{r}
## SVR-LSM (WPM - RT)
# create covariate "FPM" - rt
  FPM_rt <- filter(data_initial, condition == "FPM")
  FPM <- FPM_rt$response_time
  
# filter data according to condition
  data_WPM_rt <- filter(data_initial, condition == "WPM")

# create new data frame with relevant variables 
  data_WPM_rt <- data_WPM_rt[c('RegistryCode',
                               'age',
                               'MSO',
                               'resolution',
                               'severity',
                               'condition',
                               'response_time')]

# add covariate "FPM" to the data frame "data_WPM_rt"                                      
  data_WPM_rt <- cbind(data_WPM_rt, FPM)

# extract data frame "data_WPM_rt"
  write.csv(data_WPM_rt, here("./RData/data_WPM_rt.csv"), row.names=TRUE)


## SVR-LSM (FPM - accuracy)
# create covariate "WPM" - accuracy
  WPM_acc <- filter(data_initial, condition == "WPM")
  WPM <- WPM_acc$accuracy
  
# filter data according to condition
  data_FPM_acc <- filter(data_initial, condition == "FPM")

# create new data frame with relevant variables 
  data_FPM_acc <- data_FPM_acc[c('RegistryCode',
                                 'age',
                                 'MSO',
                                 'resolution',
                                 'severity',
                                 'condition',
                                 'accuracy')]

# add covariate "WPM" to the data frame "data_FPM_acc"                                      
  data_FPM_acc <- cbind(data_FPM_acc, WPM)

# extract data frame "data_FPM_acc"
  write.csv(data_FPM_acc, here("./RData/data_FPM_acc.csv"), row.names=TRUE)
  

## SVR-LSM (FPM - RT)
# create covariate "WPM" - rt
  WPM_rt <- filter(data_initial, condition == "WPM")
  WPM <- WPM_rt$response_time

# filter data according to condition
  data_FPM_rt <- filter(data_initial, condition == "FPM")

# create new data frame with relevant variables 
  data_FPM_rt <- data_FPM_rt[c('RegistryCode',
                                 'age',
                                 'MSO',
                                 'resolution',
                                 'severity',
                                 'condition',
                                 'response_time')]

# add covariate "WPM" to the data frame "data_FPM_rt"                                      
  data_FPM_rt <- cbind(data_FPM_rt, WPM)

# extract data frame "data_FPM_rt"
  write.csv(data_FPM_rt, here("./RData/data_FPM_rt.csv"), row.names=TRUE)
  
  
## SVR-LSM (incongruent stimuli - accuracy)
# create covariate "congruent" - accuracy 
  congruent_acc <- filter(data_initial, congruency == "congruent")
  congruent <- congruent_acc$accuracy
  
# filter data according to condition
  data_incongruent_acc <- filter(data_initial, congruency == "incongruent")

# create new data frame with relevant variables 
  data_incongruent_acc <- data_incongruent_acc[c('RegistryCode',
                                                 'age',
                                                 'MSO',
                                                 'resolution',
                                                 'severity',
                                                 'condition',
                                                 'accuracy')]
                                                 
# add covariate "congruent" to the data frame "data_incongruent_acc"                                  
  data_incongruent_acc <- cbind(data_incongruent_acc, congruent)

# extract data frame "data_incongruent_acc"
  write.csv(data_incongruent_acc, here("./RData/data_incongruent_acc.csv"), row.names=TRUE)
  
  
## SVR-LSM (incongruent stimuli - RT)
# create covariate "congruent" - rt 
  congruent_rt <- filter(data_initial, congruency == "congruent")
  congruent <- congruent_rt$response_time

# filter data according to condition
  data_incongruent_rt <- filter(data_initial, congruency == "incongruent")

# create new data frame with relevant variables 
  data_incongruent_rt <- data_incongruent_rt[c('RegistryCode',
                                                 'age',
                                                 'MSO',
                                                 'resolution',
                                                 'severity',
                                                 'condition',
                                                 'response_time')]
                                                 
# add covariate "congruent" to the data frame "data_incongruent_rt"                                  
  data_incongruent_rt <- cbind(data_incongruent_rt, congruent)

# extract data frame "data_incongruent_rt"
  write.csv(data_incongruent_rt, here("./RData/data_incongruent_rt.csv"), row.names=TRUE)
```

